export const INIT_DAILYNOTES = 'INIT_DAILYNOTES';//! not sure i will stick to this way.
export const GET_DAILYNOTES = 'GET_DAILYNOTES';
export const GET_DAYNOTE = 'GET_DAYNOTE';
export const UPDATE_DAILYNOTE='UPDATE_DAILYNOTE';
export const ADD_DAYNOTE = 'ADD_DAYNOTE';

export const SELECT_DATE = 'SELECT_DATE';

export const SELECT_MEALTYPE='SELECT_MEALTYPE';

export const ADD_MEALNOTE='ADD_MEALNOTE';

export const UPDATE_MEALNOTE = 'UPDATE_MEALNOTE';

export const TOGGLE_EDITMODE = 'TOGGLE_EDITMODE';

export const DELETE_DAILYNOTE = 'DELETE_DAILYNOTE';

export const DELETE_MEALNOTE = 'DELETE_MEALNOTE';